version: "3.8"
services:
  db:
    image: postgres:16.8
    container_name: microsrv_order__db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=microsrv_order
    ports:
      - "5432:5432"
    volumes:
      - microsrv_order__db_data:/var/lib/postgresql/data
volumes:
  microsrv_order__db_data:
